#!/usr/bin/perl
# written my Mike Habicher, mikeh@mozilla.com, August 2012.

use strict;

if( $#ARGV < 0 ) {
  # $ARGV is the array, and $#ARGV gets the highest index in the array
  print "chkdtor logcatfile\n\n";
  exit 0;
}

my $debug = 0;

my $log_file = $ARGV[0];

open( LOG, "<", "$log_file" ) or die( "$log_file: $!\n" );
my @log = <LOG> or die( "$log_file: $!\n" );
close( LOG );

my %objs = ();
my $linenum = 0;

foreach my $line( @log ) {
  $linenum += 1;
  if( $line =~ /([A-Za-z][A-Za-z0-9_]+)::(~?[A-Za-z][A-Za-z0-9_]+)\(.*\):[0-9]+ : this=0x([A-Fa-f0-9]+)/ ) {
    if( $debug ) {
      print "*";
    }
    my $class = $1;
    my $method = $2;
    my $address = $3;
    if( $debug ) {
      print "\nclass $class, method $method, address $address";
    }
    if( substr( $method, 0, 1 ) eq "~" ) {
      if( $debug ) {
        print "\ndtor $class @ $address";
      }
      $objs{ $class }{ $address } = 0;
    } elsif( $method eq $class ) {
      if( $debug ) {
        print "\nctor $class @ $address";
      }
      $objs{ $class }{ $address } = $linenum;
    }
  } else {
    if( $debug ) {
      print ".";
    }
  }
}

print "\n";

my %cleanobjs = ();

foreach my $class( keys %objs ) {
  my $showclass = 1;
  my $noleaks = 1;
  if( $debug ) {
    print "$class:\n";
    $showclass = 0;
  }
  # foreach my $addr( keys $objs{ $class } ) {
  foreach my $addr( sort { $objs{ $class }{ $a } <=> $objs{ $class }{ $b } } keys $objs{ $class } ) {
    if( $debug || $objs{ $class }{ $addr } != 0 ) {
      if( $showclass ) {
        print "$class:\n";
        $showclass = 0;
      }
      print "   $addr : $objs{ $class }{ $addr }\n";
      $noleaks = 0;
    }
  }
  if( $noleaks ) {
    $cleanobjs{ $class } = 1;
  }
}

my $showheader = 1;
foreach my $class( keys %cleanobjs ) {
  if( $showheader ) {
    print "The following classes were all cleaned up properly:\n";
    $showheader = 0;
  }
  print "   $class\n";
}
